@startuml
start
:User executes add order command using client index;

:Model gets the client from client list using index;

:Client details are copied into the order;

:Model adds the order to the order list;

:Storage saves order list after addition;
stop
@enduml
