@startuml
!include style.puml
left to right direction
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class ClientListPanel
Class ClientCard
Class IngredientListPanel
Class IngredientCard
Class RecipeCard
Class OrderListPanel
Class OrderCard
Class RecipeListPanel
Class RecipeCard
Class RevenueBarChart
Class ClientPieChart
Class RecipePieChart
Class CommandBox
Class HomeTab
Class StatTab
Class UiTab <<enumeration>>
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" HomeTab
MainWindow *-down-> "1" StatTab
MainWindow --> "0..1" HelpWindow
MainWindow ..> UiTab


HomeTab *-down-> "1" ClientListPanel
HomeTab *-down-> "1" OrderListPanel
HomeTab *-down-> "1" RecipeListPanel

StatTab *-down-> "1" IngredientListPanel
StatTab *-down-> "1" RevenueBarChart
StatTab *-down-> "1" ClientPieChart
StatTab *-down-> "1" RecipePieChart

ClientListPanel -down-> "*" ClientCard
IngredientListPanel -down-> "*" IngredientCard
OrderListPanel -down-> "*" OrderCard
RecipeListPanel -down-> "*" RecipeCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
ClientListPanel --|> UiPart
ClientCard --|> UiPart
IngredientListPanel --|> UiPart
IngredientCard --|> UiPart
OrderListPanel --|> UiPart
OrderCard --|> UiPart
RecipeListPanel --|> UiPart
RecipeCard --|> UiPart
HelpWindow --|> UiPart

ClientCard ..> Model
IngredientCard ..> Model
OrderCard ..> Model
RecipeCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

ClientListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay

MainWindow -[hidden]-|> UiPart
@enduml
